In [1]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
columns = [
    "buying",
    "maint",
    "doors",
    "persons",
    "lug_boot",
    "safety",
    "class"
]

df = pd.read_csv(
    "/content/drive/MyDrive/Colab Notebooks/dataset/car+evaluation/car.data",
    names=columns
)

df.head()

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [3]:
df_encoded = df.copy()

encoders = {}

for col in df_encoded.columns:
    le = LabelEncoder()

    df_encoded[col] = le.fit_transform(df_encoded[col])

    encoders[col] = le

    print(col, ":", list(le.classes_))

buying : ['high', 'low', 'med', 'vhigh']
maint : ['high', 'low', 'med', 'vhigh']
doors : ['2', '3', '4', '5more']
persons : ['2', '4', 'more']
lug_boot : ['big', 'med', 'small']
safety : ['high', 'low', 'med']
class : ['acc', 'good', 'unacc', 'vgood']

In [4]:
df_encoded.head()

   buying  maint  doors  persons  lug_boot  safety  class
0       3      3      0        0         2       1      2
1       3      3      0        0         2       2      2
2       3      3      0        0         2       0      2
3       3      3      0        0         1       1      2
4       3      3      0        0         1       2      2

In [6]:
X = df_encoded.drop("class", axis=1)
y = df_encoded["class"]

print(X.head())
print(y.head())

   buying  maint  doors  persons  lug_boot  safety
0       3      3      0        0         2       1
1       3      3      0        0         2       2
2       3      3      0        0         2       0
3       3      3      0        0         1       1
4       3      3      0        0         1       2
0    2
1    2
2    2
3    2
4    2
Name: class, dtype: int64

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2
)

print("학습 데이터:", X_train.shape)
print("테스트 데이터:", X_test.shape)

학습 데이터: (1382, 6)
테스트 데이터: (346, 6)

In [8]:
model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [9]:
pred_lr = model.predict(X_test)

pred_lr

array([2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2,
       0, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0,
       2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 2, 2, 2, 3, 2, 2, 2, 2,
       2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 3, 2, 2, 2, 2, 2, 2, 2,
       0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       0, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2,
       2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
print("정확도:", accuracy_score(y_test, pred_lr))

print(classification_report(y_test, pred_lr))

정확도: 0.6965317919075145
              precision    recall  f1-score   support

           0       0.35      0.11      0.17        80
           1       0.00      0.00      0.00        11
           2       0.73      0.94      0.83       243
           3       0.38      0.25      0.30        12

    accuracy                           0.70       346
   macro avg       0.36      0.33      0.32       346
weighted avg       0.61      0.70      0.63       346

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [11]:
#Decision Tree
from sklearn.tree import DecisionTreeClassifier

model_dt = DecisionTreeClassifier()

model_dt.fit(X_train, y_train)

pred_dt = model_dt.predict(X_test)

print("===== Decision Tree =====")
print("정확도:", accuracy_score(y_test, pred_dt))
print(classification_report(y_test, pred_dt))

===== Decision Tree =====
정확도: 0.9913294797687862
              precision    recall  f1-score   support

           0       1.00      0.96      0.98        80
           1       0.92      1.00      0.96        11
           2       0.99      1.00      1.00       243
           3       1.00      1.00      1.00        12

    accuracy                           0.99       346
   macro avg       0.98      0.99      0.98       346
weighted avg       0.99      0.99      0.99       346

In [12]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier()

model_rf.fit(X_train, y_train)

pred_rf = model_rf.predict(X_test)

print("===== Random Forest =====")
print("정확도:", accuracy_score(y_test, pred_rf))
print(classification_report(y_test, pred_rf))

===== Random Forest =====
정확도: 0.9653179190751445
              precision    recall  f1-score   support

           0       0.99      0.86      0.92        80
           1       0.73      1.00      0.85        11
           2       0.98      1.00      0.99       243
           3       0.92      1.00      0.96        12

    accuracy                           0.97       346
   macro avg       0.90      0.96      0.93       346
weighted avg       0.97      0.97      0.97       346

In [13]:
# KNN
from sklearn.neighbors import KNeighborsClassifier

model_knn = KNeighborsClassifier()

model_knn.fit(X_train, y_train)

pred_knn = model_knn.predict(X_test)

print("===== KNN =====")
print("정확도:", accuracy_score(y_test, pred_knn))
print(classification_report(y_test, pred_knn))

===== KNN =====
정확도: 0.8930635838150289
              precision    recall  f1-score   support

           0       0.84      0.72      0.78        80
           1       1.00      0.36      0.53        11
           2       0.90      0.99      0.94       243
           3       1.00      0.58      0.74        12

    accuracy                           0.89       346
   macro avg       0.94      0.66      0.75       346
weighted avg       0.89      0.89      0.88       346